### ISSUE TITLE
can not open structorizer

### ISSUE THREAD

**Issue by teefortwo** [fesch/Structorizer.Desktop#299]
ubuntu 16.04
jre 1.8
installed structorizer latest from following site http://structorizer.fisch.lu/

but when opening  it result is: 

java -jar $(dirname "$0")/Structorizer.app/Contents/Java/Structorizer.jar "$@"

can anyone advice?

thank you

**Comment by fesch** [comment]
Any error message on the console?

**Comment by teefortwo** [comment]
no

**Comment by fesch** [comment]
So it simply does not open?

**Comment by teefortwo** [comment]
yes 

instead a texteditor opens with that fraze

**Comment by fesch** [comment]
I see.

Your system seams to be not configured to run .sh files with the correct command interpreter. Try to launch it via the terminal.

**Comment by teefortwo** [comment]
I assume I just have to write structorizer in terminal?  sorry linux is not so well known
 structorizer
#
# A fatal error has been detected by the Java Runtime Environment:
#
#  SIGSEGV (0xb) at pc=0x00007f772058b009, pid=18316, tid=18387
#
# JRE version: OpenJDK Runtime Environment (9.0) (build 9-internal+0-2016-04-14-195246.buildd.src)
# Java VM: OpenJDK 64-Bit Server VM (9-internal+0-2016-04-14-195246.buildd.src, mixed mode, tiered, compressed oops, g1 gc, linux-amd64)
# Problematic frame:
# C  [libjava.so+0x1d009]  JNU_GetEnv+0x19
#
# Core dump will be written. Default location: Core dumps may be processed with "/usr/share/apport/apport %p %s %c %P" (or dumping to /home/bea/core.18316)
#
# An error report file with more information is saved as:
# /home/bea/hs_err_pid18316.log
#
# If you would like to submit a bug report, please visit:
#   http://bugreport.java.com/bugreport/crash.jsp
# The crash happened outside the Java Virtual Machine in native code.
# See problematic frame for where to report the bug.
#
Aborted (core dumped)

the console give the error message  

sorry the application has stopped unexpectedly 
send error report yes or no
seems like a java or system problem?

**Comment by fesch** [comment]
As this is not a java-like error message, yes, it seams to be system related or related to your java installation

**Comment by teefortwo** [comment]
ok thank you anyway I will look into that further.

**Comment by teefortwo** [comment]
Apparently structorizer does not work with jre1.8  it needs jre 1.6 wich does not exist anymore or difficult to get . is it possible to make structorizer work with jre 1.8?

**Comment by fesch** [comment]
I'm running & developing it on 1.8 !!

```
java -version
java version "1.8.0_25"
Java(TM) SE Runtime Environment (build 1.8.0_25-b17)
Java HotSpot(TM) 64-Bit Server VM (build 25.25-b02, mixed mode)
```

**Comment by teefortwo** [comment]
i have more then one system

1  mac leopard does not work anly an old version
2 ubuntu 16.04 no luck at all  open a blank container
3 windows 10   in the jar file it gives a java.lang.NoSuchMethodError
sometimes opens a container with symbols but no meny



Hoogachtend, Cordialement, Kind Regards,

Beatrice Van De Vijvere


2016-12-07 22:00 GMT+01:00 Bob Fisch <notifications@github.com>:

**Comment by teefortwo** [comment]
sorry for the poor writing

menu


Hoogachtend, Cordialement, Kind Regards,

Beatrice Van De Vijvere


2016-12-07 22:06 GMT+01:00 Bea Vdv <beavdv2000@gmail.com>:

**Comment by teefortwo** [comment]
if I open the exe file on linux with ubuntu it gives the message  "this
application requires a runtime environment 1.6.0"


Hoogachtend, Cordialement, Kind Regards,

Beatrice Van De Vijvere


2016-12-07 22:07 GMT+01:00 Bea Vdv <beavdv2000@gmail.com>:

**Comment by teefortwo** [comment]
open with Wine


Hoogachtend, Cordialement, Kind Regards,

Beatrice Van De Vijvere


2016-12-07 22:18 GMT+01:00 Bea Vdv <beavdv2000@gmail.com>:

**Comment by teefortwo** [comment]
ok
seems it works now after installing and uninstalling it 3 times, without
wine

others i have to see


Hoogachtend, Cordialement, Kind Regards,

Beatrice Van De Vijvere


2016-12-07 22:18 GMT+01:00 Bea Vdv <beavdv2000@gmail.com>:

**Comment by codemanyak** [comment]
@teefortwo 

> i have more then one system
1 mac leopard does not work anly an old version
2 ubuntu 16.04 no luck at all open a blank container
3 windows 10 in the jar file it gives a java.lang.NoSuchMethodError sometimes opens a container with symbols but no menu 

Problem on system 3 looks pretty much like issue #304. This means we have got a solution for it we could roll out pretty soon as version 3.25-10.

**Comment by codemanyak** [comment]
@teefortwo 
May we close this issue now?
Kind regards

**Comment by teefortwo** [comment]
yes for the moment


Hoogachtend, Cordialement, Kind Regards,

Beatrice Van De Vijvere


2017-01-07 11:05 GMT+01:00 Kay Gürtzig <notifications@github.com>:
